global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tetris-api'
    static_configs:
      - targets: ['tetris-api:5000']

  - job_name: 'tetris-websocket'
    static_configs:
      - targets: ['tetris-websocket:4000']
